// Curated projects. Rendered as cards in app.js.
// 6 strongest projects — chosen for breadth (CV, infra/HFT, robotics,
// agents, consumer) and shipping cred (stars + live demo).
window.PROJECTS = [
  {
    repo: "face-lock",
    title: "Face-Lock",
    desc: "Face-recognition CLI that auto-locks your laptop the moment you walk away. Computer vision + presence detection done right.",
    tag: "computer vision",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "opencv", "cli"],
    liveDemo: "https://face-lock.site",
    stars: 320,
    art: { kind: "face-lock" },
  },
  {
    repo: "btc-perp-hft-framework",
    title: "BTC-Perp HFT",
    desc: "High-frequency trading framework for BTC perpetual futures on Coinbase International. Built for low-latency research and execution.",
    tag: "hft · infra",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "trading", "low-latency"],
    liveDemo: null,
    stars: 89,
    art: { kind: "btc" },
  },
  {
    repo: "Agentic-Rescue-Drone",
    title: "Agentic Rescue Drone",
    desc: "Autonomous drone project — perception, planning, and control loop integrated for high-stakes engineering. Real hardware, real flight.",
    tag: "robotics · ml",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "ros", "cv"],
    liveDemo: null,
    stars: 156,
    art: { kind: "drone" },
  },
  {
    repo: "AI-debate-researcher",
    title: "Debate Researcher",
    desc: "Multi-agent LLM system where agents argue and refine positions with live web research. Built to actually think, not vibe.",
    tag: "agentic ai",
    lang: "PY",
    langColor: "#FFD43B",
    topics: ["python", "llm", "agents"],
    liveDemo: null,
    stars: 41,
    art: { kind: "debate" },
  },
  {
    repo: "shoppingshield",
    title: "ShoppingShield",
    desc: "Anti-scam platform that protects users from fraudulent e-commerce sites. Real-time risk scoring and browser tooling.",
    tag: "consumer · safety",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript", "security"],
    liveDemo: null,
    stars: 47,
    art: { kind: "shield" },
  },
  {
    repo: "CodeColosseum",
    title: "CodeColosseum",
    desc: "LeetCode training tool that turns grind into a tournament. Gamified competitive practice for engineers.",
    tag: "product",
    lang: "TS",
    langColor: "#3178C6",
    topics: ["typescript"],
    liveDemo: "https://codecolosseum.com",
    stars: 12,
    art: { kind: "arena" },
  },
];